---
- hosts: localhost
  vars:
    first_name: james
    last_name: bond
  tasks:
    - name: printing variables
      debug: msg='The name is {{ last_name | title }}! {{ first_name }} {{ last_name }}!'
